import type { SkillRuntimeContextSnapshot } from '@usepilot/skill-types'

export interface FinalBlindScenario {
  id: string
  category: 'colloquial' | 'context' | 'typos_synonyms' | 'collision_compound' | 'unsupported_negative'
  userPrompt: string
  expectedSkillId: string | null
  context?: SkillRuntimeContextSnapshot | undefined
  expectedInputs?: Record<string, unknown> | undefined
  expectMissingInputs?: string[] | undefined
}

/**
 * FINAL BLIND TEST CORPUS (100 Pristine, Untouched Scenarios)
 * 
 * Strict Single-Pass Benchmark. Evaluated against the frozen implementation
 * without iterative modification.
 */
export const FINAL_BLIND_CORPUS: FinalBlindScenario[] = [
  // =========================================================================
  // 1. COLLOQUIAL (20 cases)
  // =========================================================================
  {
    id: 'final-col-01',
    category: 'colloquial',
    userPrompt: 'Could you please sort out the mess of files inside ~/Downloads by extension?',
    expectedSkillId: 'organize-downloads',
    expectedInputs: { folder: '~/Downloads', groupBy: 'extension' },
  },
  {
    id: 'final-col-02',
    category: 'colloquial',
    userPrompt: 'Locate my W2 tax forms inside C:/Users/Raaz/Documents',
    expectedSkillId: 'find-files',
    expectedInputs: { directory: 'C:/Users/Raaz/Documents' },
  },
  {
    id: 'final-col-03',
    category: 'colloquial',
    userPrompt: 'Find any identical duplicate video files in ~/Videos/Recordings',
    expectedSkillId: 'duplicate-detection',
    expectedInputs: { folder: '~/Videos/Recordings' },
  },
  {
    id: 'final-col-04',
    category: 'colloquial',
    userPrompt: 'Download the technical manuals from https://docs.vendor.com/manuals into ~/Manuals',
    expectedSkillId: 'download-documents',
    expectedInputs: { url: 'https://docs.vendor.com/manuals', targetDirectory: '~/Manuals' },
  },
  {
    id: 'final-col-05',
    category: 'colloquial',
    userPrompt: 'Browse https://news.mit.edu and give me an overview of recent announcements',
    expectedSkillId: 'research-website',
    expectedInputs: { url: 'https://news.mit.edu' },
  },
  {
    id: 'final-col-06',
    category: 'colloquial',
    userPrompt: 'Organize files in ~/Desktop/MessyFolder by file type',
    expectedSkillId: 'organize-downloads',
    expectedInputs: { folder: '~/Desktop/MessyFolder', groupBy: 'fileType' },
  },
  {
    id: 'final-col-07',
    category: 'colloquial',
    userPrompt: 'Check if there are duplicate photos in C:/Users/Raaz/Pictures',
    expectedSkillId: 'duplicate-detection',
    expectedInputs: { folder: 'C:/Users/Raaz/Pictures' },
  },
  {
    id: 'final-col-08',
    category: 'colloquial',
    userPrompt: 'Search for pdf files matching invoice in ~/Work',
    expectedSkillId: 'find-files',
    expectedInputs: { directory: '~/Work', extension: 'pdf' },
  },
  {
    id: 'final-col-09',
    category: 'colloquial',
    userPrompt: 'Extract tabular pricing from https://api-service.com/pricing',
    expectedSkillId: 'extract-website-data',
    expectedInputs: { url: 'https://api-service.com/pricing' },
  },
  {
    id: 'final-col-10',
    category: 'colloquial',
    userPrompt: 'Fill out this contact form at https://help.service.com/inquiry with my information',
    expectedSkillId: 'fill-web-form',
    expectedInputs: { url: 'https://help.service.com/inquiry' },
  },
  {
    id: 'final-col-11',
    category: 'colloquial',
    userPrompt: 'Clean up all the scattered documents in ~/Downloads',
    expectedSkillId: 'organize-downloads',
    expectedInputs: { folder: '~/Downloads' },
  },
  {
    id: 'final-col-12',
    category: 'colloquial',
    userPrompt: 'Find all docx contracts in ~/Documents/Legal',
    expectedSkillId: 'find-files',
    expectedInputs: { directory: '~/Documents/Legal', extension: 'docx' },
  },
  {
    id: 'final-col-13',
    category: 'colloquial',
    userPrompt: 'Rename files in ~/Screenshots with prefix capture_',
    expectedSkillId: 'bulk-rename',
    expectedInputs: { folder: '~/Screenshots', pattern: 'capture_' },
  },
  {
    id: 'final-col-14',
    category: 'colloquial',
    userPrompt: 'Research Anthropic on https://anthropic.com and save report to ~/anthropic.md',
    expectedSkillId: 'research-and-save-report',
    expectedInputs: { url: 'https://anthropic.com', outputFilePath: '~/anthropic.md' },
  },
  {
    id: 'final-col-15',
    category: 'colloquial',
    userPrompt: 'Download all quarterly report PDFs from https://investors.apple.com to ~/Reports',
    expectedSkillId: 'download-documents',
    expectedInputs: { url: 'https://investors.apple.com', targetDirectory: '~/Reports', fileExtension: '.pdf' },
  },
  {
    id: 'final-col-16',
    category: 'colloquial',
    userPrompt: 'Download statements from https://bankportal.com/statements and sort them into ~/Finance',
    expectedSkillId: 'download-and-organize',
    expectedInputs: { url: 'https://bankportal.com/statements', destinationFolder: '~/Finance' },
  },
  {
    id: 'final-col-17',
    category: 'colloquial',
    userPrompt: 'Detect duplicate downloads in ~/Downloads',
    expectedSkillId: 'duplicate-detection',
    expectedInputs: { folder: '~/Downloads' },
  },
  {
    id: 'final-col-18',
    category: 'colloquial',
    userPrompt: 'Locate spreadsheet files matching budget in ~/Accounting',
    expectedSkillId: 'find-files',
    expectedInputs: { directory: '~/Accounting' },
  },
  {
    id: 'final-col-19',
    category: 'colloquial',
    userPrompt: 'Scrape the standings table from https://league.sports.com/standings',
    expectedSkillId: 'extract-website-data',
    expectedInputs: { url: 'https://league.sports.com/standings' },
  },
  {
    id: 'final-col-20',
    category: 'colloquial',
    userPrompt: 'Rename photos in C:/Photos to pattern vacation_',
    expectedSkillId: 'bulk-rename',
    expectedInputs: { folder: 'C:/Photos', pattern: 'vacation_' },
  },

  // =========================================================================
  // 2. CONTEXT-DEPENDENT & DEICTIC REFERENCES (20 cases)
  // =========================================================================
  {
    id: 'final-ctx-01',
    category: 'context',
    userPrompt: 'Organize this folder by date.',
    expectedSkillId: 'organize-downloads',
    context: { activeDirectory: '~/Downloads' },
    expectedInputs: { folder: '~/Downloads', groupBy: 'date' },
  },
  {
    id: 'final-ctx-02',
    category: 'context',
    userPrompt: 'Organize this folder by date.',
    expectedSkillId: 'organize-downloads',
    expectMissingInputs: ['folder'],
  },
  {
    id: 'final-ctx-03',
    category: 'context',
    userPrompt: 'Download documents from this page into ~/Downloads',
    expectedSkillId: 'download-documents',
    context: { activeBrowserUrl: 'https://docs.docker.com/engine' },
    expectedInputs: { url: 'https://docs.docker.com/engine', targetDirectory: '~/Downloads' },
  },
  {
    id: 'final-ctx-04',
    category: 'context',
    userPrompt: 'Download documents from this page into ~/Downloads',
    expectedSkillId: 'download-documents',
    expectMissingInputs: ['url'],
  },
  {
    id: 'final-ctx-05',
    category: 'context',
    userPrompt: 'Find duplicate files in this directory.',
    expectedSkillId: 'duplicate-detection',
    context: { activeDirectory: '~/Pictures' },
    expectedInputs: { folder: '~/Pictures' },
  },
  {
    id: 'final-ctx-06',
    category: 'context',
    userPrompt: 'Find duplicate files in this directory.',
    expectedSkillId: 'duplicate-detection',
    expectMissingInputs: ['folder'],
  },
  {
    id: 'final-ctx-07',
    category: 'context',
    userPrompt: 'Rename files in this folder using pattern test_',
    expectedSkillId: 'bulk-rename',
    context: { activeDirectory: '~/Projects/Testing' },
    expectedInputs: { folder: '~/Projects/Testing', pattern: 'test_' },
  },
  {
    id: 'final-ctx-08',
    category: 'context',
    userPrompt: 'Rename files in this folder using pattern test_',
    expectedSkillId: 'bulk-rename',
    expectMissingInputs: ['folder'],
  },
  {
    id: 'final-ctx-09',
    category: 'context',
    userPrompt: 'Search for pdf files here.',
    expectedSkillId: 'find-files',
    context: { activeDirectory: '~/Documents' },
    expectedInputs: { directory: '~/Documents', extension: 'pdf' },
  },
  {
    id: 'final-ctx-10',
    category: 'context',
    userPrompt: 'Search for pdf files here.',
    expectedSkillId: 'find-files',
    expectMissingInputs: ['directory'],
  },
  {
    id: 'final-ctx-11',
    category: 'context',
    userPrompt: 'Scrape the data table from this page.',
    expectedSkillId: 'extract-website-data',
    context: { activeBrowserUrl: 'https://stats.bls.gov/cpi' },
    expectedInputs: { url: 'https://stats.bls.gov/cpi' },
  },
  {
    id: 'final-ctx-12',
    category: 'context',
    userPrompt: 'Scrape the data table from this page.',
    expectedSkillId: 'extract-website-data',
    expectMissingInputs: ['url'],
  },
  {
    id: 'final-ctx-13',
    category: 'context',
    userPrompt: 'Fill this registration form with my info.',
    expectedSkillId: 'fill-web-form',
    context: { activeBrowserUrl: 'https://events.example.org/signup' },
    expectedInputs: { url: 'https://events.example.org/signup' },
  },
  {
    id: 'final-ctx-14',
    category: 'context',
    userPrompt: 'Fill this registration form with my info.',
    expectedSkillId: 'fill-web-form',
    expectMissingInputs: ['url'],
  },
  {
    id: 'final-ctx-15',
    category: 'context',
    userPrompt: 'Research this website and output summary to ~/summary.md',
    expectedSkillId: 'research-and-save-report',
    context: { activeBrowserUrl: 'https://stripe.com' },
    expectedInputs: { url: 'https://stripe.com', outputFilePath: '~/summary.md' },
  },
  {
    id: 'final-ctx-16',
    category: 'context',
    userPrompt: 'Download the documents from this site into ~/Downloads',
    expectedSkillId: 'download-documents',
    context: { activeBrowserUrl: 'https://federalreserve.gov/reports' },
    expectedInputs: { url: 'https://federalreserve.gov/reports', targetDirectory: '~/Downloads' },
  },
  {
    id: 'final-ctx-17',
    category: 'context',
    userPrompt: 'Download the reports from this site and sort into ~/Finance',
    expectedSkillId: 'download-and-organize',
    context: { activeBrowserUrl: 'https://sec.gov/filings' },
    expectedInputs: { url: 'https://sec.gov/filings', destinationFolder: '~/Finance' },
  },
  {
    id: 'final-ctx-18',
    category: 'context',
    userPrompt: 'Tidy up this folder.',
    expectedSkillId: 'organize-downloads',
    context: { activeDirectory: '~/Desktop/Mess' },
    expectedInputs: { folder: '~/Desktop/Mess' },
  },
  {
    id: 'final-ctx-19',
    category: 'context',
    userPrompt: 'Check for redundant copies in this folder.',
    expectedSkillId: 'duplicate-detection',
    context: { activeDirectory: '~/Documents/Drafts' },
    expectedInputs: { folder: '~/Documents/Drafts' },
  },
  {
    id: 'final-ctx-20',
    category: 'context',
    userPrompt: 'Overview this website.',
    expectedSkillId: 'research-website',
    context: { activeBrowserUrl: 'https://fly.io' },
    expectedInputs: { url: 'https://fly.io' },
  },

  // =========================================================================
  // 3. VARIATIONS, TYPOS & SYNONYMS (20 cases)
  // =========================================================================
  {
    id: 'final-var-01',
    category: 'typos_synonyms',
    userPrompt: 'organise my downlaods folder',
    expectedSkillId: 'organize-downloads',
    expectedInputs: { folder: '~/Downloads' },
  },
  {
    id: 'final-var-02',
    category: 'typos_synonyms',
    userPrompt: 'find invoise pdf files in ~/Documents',
    expectedSkillId: 'find-files',
    expectedInputs: { directory: '~/Documents', extension: 'pdf' },
  },
  {
    id: 'final-var-03',
    category: 'typos_synonyms',
    userPrompt: 'reaserch https://cloudflare.com',
    expectedSkillId: 'research-website',
    expectedInputs: { url: 'https://cloudflare.com' },
  },
  {
    id: 'final-var-04',
    category: 'typos_synonyms',
    userPrompt: 'duplicat files in ~/Downloads',
    expectedSkillId: 'duplicate-detection',
    expectedInputs: { folder: '~/Downloads' },
  },
  {
    id: 'final-var-05',
    category: 'typos_synonyms',
    userPrompt: 'renmae files in ~/Screenshots with pattern img_',
    expectedSkillId: 'bulk-rename',
    expectedInputs: { folder: '~/Screenshots', pattern: 'img_' },
  },
  {
    id: 'final-var-06',
    category: 'typos_synonyms',
    userPrompt: 'downlaod pdf documents from https://irs.gov/forms to ~/Taxes',
    expectedSkillId: 'download-documents',
    expectedInputs: { url: 'https://irs.gov/forms', targetDirectory: '~/Taxes', fileExtension: '.pdf' },
  },
  {
    id: 'final-var-07',
    category: 'typos_synonyms',
    userPrompt: 'fil form at https://portal.company.com/apply',
    expectedSkillId: 'fill-web-form',
    expectedInputs: { url: 'https://portal.company.com/apply' },
  },
  {
    id: 'final-var-08',
    category: 'typos_synonyms',
    userPrompt: 'sort ~/Downloads by fileType',
    expectedSkillId: 'organize-downloads',
    expectedInputs: { folder: '~/Downloads', groupBy: 'fileType' },
  },
  {
    id: 'final-var-09',
    category: 'typos_synonyms',
    userPrompt: 'seek receipt files in ~/Documents',
    expectedSkillId: 'find-files',
    expectedInputs: { directory: '~/Documents' },
  },
  {
    id: 'final-var-10',
    category: 'typos_synonyms',
    userPrompt: 'find identical files in ~/Music',
    expectedSkillId: 'duplicate-detection',
    expectedInputs: { folder: '~/Music' },
  },
  {
    id: 'final-var-11',
    category: 'typos_synonyms',
    userPrompt: 'fetch pdf reports from https://data.gov/reports into ~/Downloads',
    expectedSkillId: 'download-documents',
    expectedInputs: { url: 'https://data.gov/reports', targetDirectory: '~/Downloads', fileExtension: '.pdf' },
  },
  {
    id: 'final-var-12',
    category: 'typos_synonyms',
    userPrompt: 'investigate website https://openai.com',
    expectedSkillId: 'research-website',
    expectedInputs: { url: 'https://openai.com' },
  },
  {
    id: 'final-var-13',
    category: 'typos_synonyms',
    userPrompt: 'tidy C:/Users/Raaz/Downloads',
    expectedSkillId: 'organize-downloads',
    expectedInputs: { folder: 'C:/Users/Raaz/Downloads' },
  },
  {
    id: 'final-var-14',
    category: 'typos_synonyms',
    userPrompt: 'locate all spreadsheet files in ~/Desktop',
    expectedSkillId: 'find-files',
    expectedInputs: { directory: '~/Desktop' },
  },
  {
    id: 'final-var-15',
    category: 'typos_synonyms',
    userPrompt: 'check dupes in ~/Downloads',
    expectedSkillId: 'duplicate-detection',
    expectedInputs: { folder: '~/Downloads' },
  },
  {
    id: 'final-var-16',
    category: 'typos_synonyms',
    userPrompt: 'harvest table data from https://coingecko.com/markets',
    expectedSkillId: 'extract-website-data',
    expectedInputs: { url: 'https://coingecko.com/markets' },
  },
  {
    id: 'final-var-17',
    category: 'typos_synonyms',
    userPrompt: 'complete registration at https://community.org/register',
    expectedSkillId: 'fill-web-form',
    expectedInputs: { url: 'https://community.org/register' },
  },
  {
    id: 'final-var-18',
    category: 'typos_synonyms',
    userPrompt: 'grab docs from https://docs.python.org into ~/PythonDocs',
    expectedSkillId: 'download-documents',
    expectedInputs: { url: 'https://docs.python.org', targetDirectory: '~/PythonDocs' },
  },
  {
    id: 'final-var-19',
    category: 'typos_synonyms',
    userPrompt: 'find redundant files in ~/Projects',
    expectedSkillId: 'duplicate-detection',
    expectedInputs: { folder: '~/Projects' },
  },
  {
    id: 'final-var-20',
    category: 'typos_synonyms',
    userPrompt: 'arrange ~/Downloads by date',
    expectedSkillId: 'organize-downloads',
    expectedInputs: { folder: '~/Downloads', groupBy: 'date' },
  },

  // =========================================================================
  // 4. COLLISIONS & COMPOUNDS (20 cases)
  // =========================================================================
  {
    id: 'final-coll-01',
    category: 'collision_compound',
    userPrompt: 'Find files named statement in ~/Documents',
    expectedSkillId: 'find-files',
    expectedInputs: { directory: '~/Documents' },
  },
  {
    id: 'final-coll-02',
    category: 'collision_compound',
    userPrompt: 'Find duplicate statements in ~/Documents',
    expectedSkillId: 'duplicate-detection',
    expectedInputs: { folder: '~/Documents' },
  },
  {
    id: 'final-coll-03',
    category: 'collision_compound',
    userPrompt: 'Download statements from https://bank.com/statements into ~/Statements',
    expectedSkillId: 'download-documents',
    expectedInputs: { url: 'https://bank.com/statements', targetDirectory: '~/Statements' },
  },
  {
    id: 'final-coll-04',
    category: 'collision_compound',
    userPrompt: 'Download statements from https://bank.com/statements and sort them into ~/Finance',
    expectedSkillId: 'download-and-organize',
    expectedInputs: { url: 'https://bank.com/statements', destinationFolder: '~/Finance' },
  },
  {
    id: 'final-coll-05',
    category: 'collision_compound',
    userPrompt: 'Sort statements in ~/Finance by date',
    expectedSkillId: 'organize-downloads',
    expectedInputs: { folder: '~/Finance', groupBy: 'date' },
  },
  {
    id: 'final-coll-06',
    category: 'collision_compound',
    userPrompt: 'Rename statements in ~/Finance with pattern bank_2026_',
    expectedSkillId: 'bulk-rename',
    expectedInputs: { folder: '~/Finance', pattern: 'bank_2026_' },
  },
  {
    id: 'final-coll-07',
    category: 'collision_compound',
    userPrompt: 'Research company https://nvidia.com',
    expectedSkillId: 'research-website',
    expectedInputs: { url: 'https://nvidia.com' },
  },
  {
    id: 'final-coll-08',
    category: 'collision_compound',
    userPrompt: 'Research company https://nvidia.com and save report to ~/nvidia.md',
    expectedSkillId: 'research-and-save-report',
    expectedInputs: { url: 'https://nvidia.com', outputFilePath: '~/nvidia.md' },
  },
  {
    id: 'final-coll-09',
    category: 'collision_compound',
    userPrompt: 'Extract pricing data table from https://nvidia.com/cloud-pricing',
    expectedSkillId: 'extract-website-data',
    expectedInputs: { url: 'https://nvidia.com/cloud-pricing' },
  },
  {
    id: 'final-coll-10',
    category: 'collision_compound',
    userPrompt: 'Fill inquiry form on https://nvidia.com/enterprise-contact',
    expectedSkillId: 'fill-web-form',
    expectedInputs: { url: 'https://nvidia.com/enterprise-contact' },
  },
  {
    id: 'final-coll-11',
    category: 'collision_compound',
    userPrompt: 'Find all PDF documents in C:/Users/Raaz/Downloads',
    expectedSkillId: 'find-files',
    expectedInputs: { directory: 'C:/Users/Raaz/Downloads', extension: 'pdf' },
  },
  {
    id: 'final-coll-12',
    category: 'collision_compound',
    userPrompt: 'Find duplicate PDF documents in C:/Users/Raaz/Downloads',
    expectedSkillId: 'duplicate-detection',
    expectedInputs: { folder: 'C:/Users/Raaz/Downloads' },
  },
  {
    id: 'final-coll-13',
    category: 'collision_compound',
    userPrompt: 'Download PDF documents from https://irs.gov/forms into ~/TaxForms',
    expectedSkillId: 'download-documents',
    expectedInputs: { url: 'https://irs.gov/forms', targetDirectory: '~/TaxForms', fileExtension: '.pdf' },
  },
  {
    id: 'final-coll-14',
    category: 'collision_compound',
    userPrompt: 'Download IRS PDF documents from https://irs.gov/forms and organize them in ~/Taxes',
    expectedSkillId: 'download-and-organize',
    expectedInputs: { url: 'https://irs.gov/forms', destinationFolder: '~/Taxes' },
  },
  {
    id: 'final-coll-15',
    category: 'collision_compound',
    userPrompt: 'Organize PDF documents in ~/Taxes by date',
    expectedSkillId: 'organize-downloads',
    expectedInputs: { folder: '~/Taxes', groupBy: 'date' },
  },
  {
    id: 'final-coll-16',
    category: 'collision_compound',
    userPrompt: 'Rename tax forms in ~/Taxes using prefix irs_2025_',
    expectedSkillId: 'bulk-rename',
    expectedInputs: { folder: '~/Taxes', pattern: 'irs_2025_' },
  },
  {
    id: 'final-coll-17',
    category: 'collision_compound',
    userPrompt: 'Extract financial balance sheet table from https://finance.yahoo.com/quote/AAPL/balance-sheet',
    expectedSkillId: 'extract-website-data',
    expectedInputs: { url: 'https://finance.yahoo.com/quote/AAPL/balance-sheet' },
  },
  {
    id: 'final-coll-18',
    category: 'collision_compound',
    userPrompt: 'Research Apple financial health at https://apple.com/investors and save report to ~/apple_report.md',
    expectedSkillId: 'research-and-save-report',
    expectedInputs: { url: 'https://apple.com/investors', outputFilePath: '~/apple_report.md' },
  },
  {
    id: 'final-coll-19',
    category: 'collision_compound',
    userPrompt: 'Find all log files in /var/log',
    expectedSkillId: 'find-files',
    expectedInputs: { directory: '/var/log' },
  },
  {
    id: 'final-coll-20',
    category: 'collision_compound',
    userPrompt: 'Identify duplicate log files in /var/log',
    expectedSkillId: 'duplicate-detection',
    expectedInputs: { folder: '/var/log' },
  },

  // =========================================================================
  // 5. UNSEEN OUT-OF-DOMAIN / UNSUPPORTED (20 cases)
  // Must return null (rejected with no match)
  // =========================================================================
  {
    id: 'final-neg-01',
    category: 'unsupported_negative',
    userPrompt: 'Can you help me prepare a budget spreadsheet for our household?',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-02',
    category: 'unsupported_negative',
    userPrompt: 'Play classical Mozart radio on YouTube Music.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-03',
    category: 'unsupported_negative',
    userPrompt: 'Translate this Japanese text into English for my email.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-04',
    category: 'unsupported_negative',
    userPrompt: 'Help me debug a null pointer exception in Java Spring Boot.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-05',
    category: 'unsupported_negative',
    userPrompt: 'What is the current population of Tokyo?',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-06',
    category: 'unsupported_negative',
    userPrompt: 'Draft an email to my manager asking for a salary increase.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-07',
    category: 'unsupported_negative',
    userPrompt: 'Calculate my target heart rate zone for cardio endurance training.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-08',
    category: 'unsupported_negative',
    userPrompt: 'Solve this calculus derivative: d/dx of sin(x^2).',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-09',
    category: 'unsupported_negative',
    userPrompt: 'Book an Uber ride from SFO airport to downtown San Francisco.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-10',
    category: 'unsupported_negative',
    userPrompt: 'Recommend a good lightweight JavaScript charting library for React.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-11',
    category: 'unsupported_negative',
    userPrompt: 'Explain how the Raft consensus algorithm handles leader election.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-12',
    category: 'unsupported_negative',
    userPrompt: 'Draft a confidentiality NDA agreement for a contractor in California.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-13',
    category: 'unsupported_negative',
    userPrompt: 'Write an optimized SQL migration script adding indexes to user_accounts.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-14',
    category: 'unsupported_negative',
    userPrompt: 'Order two iced lattes from Starbucks on DoorDash.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-15',
    category: 'unsupported_negative',
    userPrompt: 'What is the forecast weather for Denver this weekend?',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-16',
    category: 'unsupported_negative',
    userPrompt: 'Create a slide deck outline for our seed round investor meeting.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-17',
    category: 'unsupported_negative',
    userPrompt: 'Teach me how to tune a six-string acoustic guitar.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-18',
    category: 'unsupported_negative',
    userPrompt: 'Transcribe this audio interview file into clean formatted text.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-19',
    category: 'unsupported_negative',
    userPrompt: 'Send a Slack message to the engineering channel announcing deployment.',
    expectedSkillId: null,
  },
  {
    id: 'final-neg-20',
    category: 'unsupported_negative',
    userPrompt: 'Plan a 5-day hiking itinerary in Banff National Park.',
    expectedSkillId: null,
  },
]
